Version 2
YunoHost-Apps/gitea_ynh pull request #69
Opened 2023-02-23 23:09 UTC by ericgaspar

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2023-02-23 23:09 UTC, ericgaspar commented
!testme

2023-02-24 00:57 UTC, alexAubin commented on manifest.toml
> +    admin.allowed = ["admin"]
```suggestion
    admin.allowed = ["admins"]
```

2023-02-24 00:59 UTC, alexAubin commented on manifest.toml
> +    type = "user"
I'm not sure this question is still useful now if we go with `admin.allowed = ["admins"]` below ...

Or another way is to have a question named `init_admin_permission` and remove the `admin.allowed` line (but then we still need something to declare that the admin permission does exists

2023-02-24 07:14 UTC, Josue-T requested changes

2023-02-24 07:14 UTC, Josue-T commented on scripts/upgrade
> -;&
As already explained many time like [here](https://github.com/YunoHost-Apps/gitea_ynh/pull/45#discussion_r884315843), please keep this as it is.

2023-02-24 08:28 UTC, ericgaspar commented
!testme

2023-03-01 08:41 UTC, closed without merging